### ISSUE TITLE
Postgres incompatibility

### ISSUE THREAD

**Issue by imandr** [rucio/rucio#738]
Motivation
----------
I am using rucio with Postgres 9.5 backend. I am getting the following error in the covneyor transfer submitter:

2018-02-21 20:33:54,140    120    CRITICAL    0:0 Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/rucio/daemons/conveyor/submitter.py", line 135, in submitter
   retry_other_fts=retry_other_fts)
 File "/usr/lib/python2.7/site-packages/rucio/daemons/conveyor/submitter.py", line 268, in __get_transfers
   failover_schemes=failover_schemes)
 File "/usr/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
   return Retrying(*dargs, **dkw).call(f, *args, **kw)
 File "/usr/lib/python2.7/site-packages/retrying.py", line 206, in call
   return attempt.get(self._wrap_exception)
 File "/usr/lib/python2.7/site-packages/retrying.py", line 247, in get
   six.reraise(self.value[0], self.value[1], self.value[2])
 File "/usr/lib/python2.7/site-packages/retrying.py", line 200, in call
   attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
 File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 274, in new_funct
   raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (psycopg2.ProgrammingError) function md5(uuid) does not exist
LINE 4: ...activity = 'User Subscriptions' AND mod(abs(('x'||md5(rule_i...

the SQL is: SELECT anon_1.id AS anon_1_id, anon_1.rule_id AS anon_1_rule_id, anon_1.scope AS anon_1_scope, anon_1.name AS anon_1_name, anon_1.md5 AS anon_1_md5, anon_1.adler32 AS anon_1_adler32, anon_1.bytes AS anon_1_bytes, anon_1.activity AS anon_1_activity, anon_1.attributes AS anon_1_attributes, anon_1.previous_attempt_id AS anon_1_previous_attempt_id, anon_1.dest_rse_id AS anon_1_dest_rse_id, replicas.rse_id AS replicas_rse_id, rses.rse AS rses_rse, rses.deterministic AS rses_deterministic, rses.rse_type AS rses_rse_type, replicas.path AS replicas_path, anon_1.retry_count AS anon_1_retry_count, sources.url AS sources_url, sources.ranking AS sources_ranking, distances.ranking AS distances_ranking \nFROM (SELECT requests.id AS id, requests.rule_id AS rule_id, requests.scope AS scope, requests.name AS name, requests.md5 AS md5, requests.adler32 AS adler32, requests.bytes AS bytes, requests.activity AS activity, requests.attributes AS attributes, requests.previous_attempt_id AS previous_attempt_id, requests.dest_rse_id AS dest_rse_id, requests.retry_count AS retry_count \nFROM requests \nWHERE requests.state = %(state_1)s AND requests.request_type = %(request_type_1)s AND requests.activity = %(activity_1)s AND mod(abs(('x'||md5(rule_id))::bit(32)::int), 1) = 0 \n LIMIT %(param_1)s) AS anon_1 LEFT OUTER JOIN replicas ON anon_1.scope = replicas.scope AND anon_1.name = replicas.name AND replicas.state = %(state_2)s AND anon_1.dest_rse_id != replicas.rse_id LEFT OUTER JOIN rses ON rses.id = replicas.rse_id AND rses.staging_area = false AND rses.deleted = false LEFT OUTER JOIN sources ON anon_1.id = sources.request_id AND rses.id = sources.rse_id LEFT OUTER JOIN distances ON anon_1.dest_rse_id = distances.dest_rse_id AND replicas.rse_id = distances.src_rse_id

Modification
------------
I think it can be fixed by changing the SQL fragment 
   mod(abs(('x'||md5(rule_id))::bit(32)::int), 1)

to 
  mod(abs(('x'||md5(rule_id::text))::bit(32)::int), 1)

**Comment by imandr** [comment]
I found same problem in core/request.py:

        if (total_processes - 1) > 0:
            if session.bind.dialect.name == 'oracle':
                bindparams = [bindparam('process_number', process), bindparam('total_processes', total_processes - 1)]
                query = query.filter(text('ORA_HASH(rule_id, :total_processes) = :process_number', bindparams=bindparams))
            elif session.bind.dialect.name == 'mysql':
                query = query.filter(text('mod(md5(rule_id), %s) = %s' % (total_processes - 1, process)))
            elif session.bind.dialect.name == 'postgresql':
                query = query.filter(text('mod(abs((\'x\'||md5(rule_id::text))::bit(32)::int), %s) = %s' % (total_processes - 1, process)))

        if (total_threads - 1) > 0:
            if session.bind.dialect.name == 'oracle':
                bindparams = [bindparam('thread_number', thread), bindparam('total_threads', total_threads - 1)]
                query = query.filter(text('ORA_HASH(rule_id, :total_threads) = :thread_number', bindparams=bindparams))
            elif session.bind.dialect.name == 'mysql':
                query = query.filter(text('mod(md5(rule_id), %s) = %s' % (total_threads - 1, thread)))
            elif session.bind.dialect.name == 'postgresql':
                query = query.filter(text('mod(abs((\'x\'||md5(rule_id::text))::bit(32)::int), %s) = %s' % (total_threads - 1, thread)))

**Comment by imandr** [comment]
In fact, I found the same in many other places:
[rucio@ruciodev01 core]$ grep md5 *.py|grep filter | grep -v name
account_counter.py:            query = query.filter('mod(md5(concat(account, rse_id)), %s) = %s' % (total_workers + 1, worker_number))
account_counter.py:            query = query.filter('mod(abs((\'x\'||md5(concat(account, rse_id)))::bit(32)::int), %s) = %s' % (total_workers + 1, worker_number))
message.py:                subquery = subquery.filter('mod(md5(id), %s) = %s' % (total_threads - 1, thread))
message.py:                subquery = subquery.filter('mod(abs((\'x\'||md5(id))::bit(32)::int), %s) = %s' % (total_threads - 1, thread))
quarantined_replica.py:            query = query.filter('mod(md5(path), %s) = %s' % (total_workers - 1, worker_number - 1))
quarantined_replica.py:            query = query.filter('mod(abs((\'x\'||md5(path))::bit(32)::int), %s) = %s' % (total_workers - 1, worker_number - 1))
replica.py:                      models.DataIdentifier.md5).with_hint(models.DataIdentifier, "INDEX(dids DIDS_PK)", 'oracle').filter(condition)
request.py:                query = query.filter(text('mod(md5(rule_id), %s) = %s' % (total_processes - 1, process)))
request.py:                query = query.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_processes - 1, process)))
request.py:                query = query.filter(text('mod(md5(rule_id), %s) = %s' % (total_threads - 1, thread)))
request.py:                query = query.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_threads - 1, thread)))
request.py:            sub_requests = sub_requests.filter(text('mod(md5(rule_id), %s) = %s' % (total_processes - 1, process)))
request.py:            sub_requests = sub_requests.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_processes - 1, process)))
request.py:            sub_requests = sub_requests.filter(text('mod(md5(rule_id), %s) = %s' % (total_threads - 1, thread)))
request.py:            sub_requests = sub_requests.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_threads - 1, thread)))
rse_counter.py:            query = query.filter('mod(md5(rse_id), %s) = %s' % (total_workers + 1, worker_number))
rse_counter.py:            query = query.filter('mod(abs((\'x\'||md5(rse_id))::bit(32)::int), %s) = %s' % (total_workers + 1, worker_number))
rule.py:                    md5, bytes, adler32 = session.query(models.RSEFileAssociation.md5, models.RSEFileAssociation.bytes, models.RSEFileAssociation.adler32).filter(models.RSEFileAssociation.scope == lock.scope,
temporary_did.py:            query = query.filter(text('mod(abs((\'x\'||md5(path))::bit(32)::int), %s) = %s' % (total_workers - 1, worker_number - 1)))
transfer.py:                query = query.filter(text('mod(md5(rule_id), %s) = %s' % (total_processes - 1, process)))
transfer.py:                query = query.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_processes - 1, process)))
transfer.py:                query = query.filter(text('mod(md5(rule_id), %s) = %s' % (total_threads - 1, thread)))
transfer.py:                query = query.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_threads - 1, thread)))
transfer.py:            sub_requests = sub_requests.filter(text('mod(md5(rule_id), %s) = %s' % (total_processes - 1, process)))
transfer.py:            sub_requests = sub_requests.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_processes - 1, process)))
transfer.py:            sub_requests = sub_requests.filter(text('mod(md5(rule_id), %s) = %s' % (total_threads - 1, thread)))
transfer.py:            sub_requests = sub_requests.filter(text('mod(abs((\'x\'||md5(rule_id))::bit(32)::int), %s) = %s' % (total_threads - 1, thread)))

**Comment by mlassnig** [comment]
Hi,

we are usually testing against PostgreSQL 9.6+, this looks like a backward incompatibility.

Can you try to apply your fix and run the test-suite to see if it fixes your problem? The automatic checker in Travis will do the same for 9.6 so we can immediately see if there's a regression.

**Comment by imandr** [comment]
I applied the change to the request.py and transfer.py and tested it, and it works fine with Postgres 9.5

**Comment by mlassnig** [comment]
@imandr can you make a pull request please? thanks!

$ tools/create-patch-branch 738 "database: postgres incompatibility"
$ emacs
$ git add
$ git commit
$ tools/submit-pull-request

**Comment by vingar** [comment]
Cf. https://github.com/rucio/rucio/blob/master/CONTRIBUTING.rst

**Comment by imandr** [comment]
when I do tools/submit-pull-request, I get this:

[rucio@ruciodev01 rucio_cern]$ ./tools/submit-pull-request
Traceback (most recent call last):
  File "./tools/submit-pull-request", line 18, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'urllib3'

**Comment by vingar** [comment]
Maybe some incompatibilities in the environment. 

You can try from a virtualenv with

```
python tools/install_venv.py 
source .venv/bin/activate
```

**Comment by imandr** [comment]
[rucio@ruciodev01 rucio_cern]$ python tools/install_venv.py 
which: no virtualenv in (/usr/lib64/qt-3.3/bin:/opt/puppetlabs/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/rucio/.local/bin:/home/rucio/bin)
Failed to install virtualenv with curl.
Creating venv via curl...
[rucio@ruciodev01 rucio_cern]$ source .venv/bin/activate
-bash: .venv/bin/activate: No such file or directory

**Comment by mlassnig** [comment]
Your hostmachine needs to have virtualenv installed (either via pip, apt-get or yum), that should solve it.

**Comment by vingar** [comment]
virtualenv is not in your environment. `pip install virtualenv` or get it from https://raw.github.com/pypa/virtualenv/master/virtualenv.py

**Comment by imandr** [comment]
(.venv) [rucio@ruciodev01 rucio_cern]$ ./tools/submit-pull-request
Loading github OAUTH token ... ERROR
No github token file found at /home/rucio/rucio_cern/.githubtoken

**Comment by imandr** [comment]
(.venv) [rucio@ruciodev01 rucio_cern]$ ls -la
total 172
drwxrwxr-x. 10 rucio rucio  4096 Feb 23 15:32 .
drwxr-xr-x. 14 rucio rucio  4096 Feb 23 13:09 ..
-rw-rw-r--.  1 rucio rucio  2175 Feb 23 10:45 AUTHORS.rst
drwxrwxr-x.  3 rucio rucio  4096 Feb 23 10:45 bin
-rw-rw-r--.  1 rucio rucio   273 Feb  1 13:16 ChangeLog
-rw-rw-r--.  1 rucio rucio  5547 Feb 23 10:45 CONTRIBUTING.rst
drwxrwxr-x.  5 rucio rucio  4096 Feb  1 13:16 doc
drwxrwxr-x.  9 rucio rucio  4096 Feb 23 10:45 etc
drwxrwxr-x.  2 rucio rucio  4096 Feb  1 13:16 externals
-rw-rw-r--.  1 rucio rucio    41 Feb  1 13:16 .flake8
drwxrwxr-x.  8 rucio rucio  4096 Feb 23 10:54 .git
-rw-rw-r--.  1 rucio rucio  1037 Feb  1 13:16 .gitignore
-rw-rw-r--.  1 rucio rucio    49 Feb 23 10:45 ISSUE_TEMPLATE.md
drwxrwxr-x.  3 rucio rucio  4096 Feb  1 13:16 lib
-rw-rw-r--.  1 rucio rucio 11357 Feb  1 13:16 LICENSE
-rw-rw-r--.  1 rucio rucio   737 Feb  1 13:16 MANIFEST.in.client
-rw-rw-r--.  1 rucio rucio   919 Feb  1 13:16 MANIFEST.in.rucio
-rw-rw-r--.  1 rucio rucio   432 Feb  1 13:16 MANIFEST.in.webui
-rw-rw-r--.  1 rucio rucio    28 Feb  1 13:16 .pep8
-rw-rw-r--.  1 rucio rucio   500 Feb  1 13:16 PULL_REQUEST_TEMPLATE.md
-rw-rw-r--.  1 rucio rucio  7508 Feb  1 13:16 pylintrc
-rw-rw-r--.  1 rucio rucio  1250 Feb  1 13:16 README.client.rst
-rw-rw-r--.  1 rucio rucio  1544 Feb 23 10:45 README.rst
-rw-rw-r--.  1 rucio rucio  1235 Feb  1 13:16 README.rucio.rst
-rw-rw-r--.  1 rucio rucio  1245 Feb  1 13:16 README.webui.rst
-rw-rw-r--.  1 rucio rucio  5907 Feb 23 10:45 requirements.readthedocs.txt
lrwxrwxrwx.  1 rucio rucio     9 Feb 23 10:45 rucio -> lib/rucio
-rw-rw-r--.  1 rucio rucio  1014 Feb  1 13:16 setup.cfg
-rw-rw-r--.  1 rucio rucio  7841 Feb 23 10:45 setup.py
-rw-rw-r--.  1 rucio rucio  5697 Feb  1 13:16 setup_rucio_client.py
-rw-rw-r--.  1 rucio rucio  5845 Feb  1 13:16 setup_rucio.py
-rw-rw-r--.  1 rucio rucio  3011 Feb  1 13:16 setup_webui.py
drwxrwxr-x.  6 rucio rucio  4096 Feb 23 10:45 tools
-rw-rw-r--.  1 rucio rucio  2228 Feb  1 13:16 tox.ini
-rw-rw-r--.  1 rucio rucio  1086 Feb 23 10:45 .travis.yml
drwxrwxr-x.  7 rucio rucio  4096 Feb 23 15:33 .venv

**Comment by mlassnig** [comment]
If you go here you can create a github access token:

https://github.com/settings/tokens

Generate a new token (just put all permissions for simplicity's sake) and write the token to a new file .githubtoken

That should solve it.

@bari12 we need to add this to the development guidelines ;-)

**Comment by imandr** [comment]
I created the token:

(.venv) [rucio@ruciodev01 rucio_cern]$ ls -lad .git*
drwxrwxr-x. 8 rucio rucio 4096 Feb 23 16:43 .git
-rw-------. 1 rucio rucio   41 Feb 23 16:34 .githubtoken
-rw-rw-r--. 1 rucio rucio 1037 Feb  1 13:16 .gitignore

and now I am getting this error:

(.venv) [rucio@ruciodev01 rucio_cern]$ ./tools/submit-pull-request
Loading github OAUTH token ... OK
Checking if current branch is a patch/feature/hotfix branch ... OK
Username for 'https://github.com': imandr
Password for 'https://imandr@github.com': 
Pushing the feature/patch/hotfix branch to origin ... ERROR
remote: Permission to rucio/rucio.git denied to imandr.
fatal: unable to access 'https://github.com/rucio/rucio.git/': The requested URL returned error: 403

**Comment by mlassnig** [comment]
Did you fork the repository and clone your forked repository (imandr/rucio)?

This looks like you tried to clone the upstream repository (rucio/rucio). Submission to the upstream repository can only be done through merge requests from private forked repositories.

**Comment by imandr** [comment]
No I did not initially, but now I did.

I went to GitHub and forked yours into mine.
Then I cloned it: 
```
git clone https://github.com/imandr/rucio.git my_forked
```
Then I installed virualenv: 
```
cd my_forked
python tools/install_venv.py 
```
Then I activated it:
```
source .venv/bin/activate
```
Now I am trying to create the patch branch and I am getting new error:
```
(.venv) [rucio@ruciodev01 my_forked]$ tools/create-patch-branch 738 "database: postgres incompatibility"
Switching to master
Already on 'master'
Updating master
Fetching origin
Already up-to-date.
Rebasing master
fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Can't rebase to master. Unstaged changes?
```

**Comment by imandr** [comment]
Ok, never mind, I added "upstream" remote with same URL as "origin", which is the URL of my fork, and that error is gone now.
