### PR TITLE
Lifetime Model: Fix fetching rules beyond EOL #4519

### LINKED ISSUE #4519: Atropos can’t fetch the list of rules beyond EOL
Motivation
----------

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/atropos/atropos.py", line 110, in atropos
    rses = parse_expression(rule.rse_expression, filter={'vo': rule.account.vo})
AttributeError: 'result' object has no attribute 'account'
```

This bug was introduced with commit ec57f5731f.

Modification
------------

Simply add `account` to the returned columns of `get_rules_beyond_eol()`.

### PR DESCRIPTION
**Pull request by dchristidis**
Fixes #4519.

### CODE REVIEW

**Comment by cserf** [comment]
LGTM

**Review by cserf — APPROVED** [review]
