### PR TITLE
Replicas: Fix variable name bug in add_bad_dids #5642

### LINKED ISSUE #5642: Declare a list of bad replicas bug
Motivation
----------
The `add_bad_dids` function in `core` creates a temporary list of dids from the input, which should be used to determine the replicas. This list (falsely labeled as `replicas_list`) https://github.com/rucio/rucio/blob/21c93bd7d02dbc70bc3127ad77fb1a1981b83058/lib/rucio/core/replica.py#L352 however is never filled. Instead, the `list_replicas` function tries to be filled https://github.com/rucio/rucio/blob/21c93bd7d02dbc70bc3127ad77fb1a1981b83058/lib/rucio/core/replica.py#L357

This should throw an error.

The bug got introduced in https://github.com/rucio/rucio/commit/f432881425d62aa35979a0b726c2c2ea512abcd2, the `add_bad_dids` function is not tested.

Modification
------------
Resolve the bug, add tests.

### PR DESCRIPTION
**Pull request by joeldierkes**
The temporary list of replicas to mark as _BAD_ is not references
correctly. Instead, a function is referenced. This produces an
`AttributeError: 'function' object has no attribute 'append'` exception.

### CODE REVIEW

**Comment by joeldierkes** [comment]
This one is good to go. The issue in the pipeline comes from https://github.com/rucio/rucio/issues/5658, I'm still investigating.

**Review by rcarpa — APPROVED** [review]
