### ISSUE TITLE
rucio replica list dataset --rse crashes with the rich CLI renderer

### ISSUE THREAD

**Issue by VladGaluska** [rucio/rucio#8641]
### Description

`rucio replica list dataset --rse <RSE>` crashes with exit code 1 when the rich CLI rendered is enabled. 
`lib/rucio/cli/replica.py` line 330 reads `ctx.obj.args.no_pager` instead of `ctx.obj.no_pager`. Since `Arguments.__getattr__` is `dict.get`, `ctx.obj.args` silently returns `None`, so the call raises `AttributeError: 'NoneType' object has no attribute 'no_pager'`.
I believe this was introduced in #8447 , but was not caught in the tests due to the cli renderer not actually being used for those, which I created a PR for in #8588 .

### Steps to reproduce

1. Switch rucio to use the CLi renderer:
```shell
cp /opt/rucio/etc/rucio.cfg /tmp/rucio_rich.cfg
printf '\n[experimental]\ncli = rich\n' >> /tmp/rucio_rich.cfg
printf '\n[experimental]\ncli = rich\n' >> /tmp/rucio_rich.cfg
```
2. Run the rucio replica list dataset --rse <RSE> command:
```shell
rucio replica list dataset --rse MOCK
```
